name: Update Data

concurrency:
  group: "main"
  cancel-in-progress: false

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Install requirements
        run: |
          cd python
          python3 -m pip install --upgrade pip 
          python3 -m pip install -r requirements.txt
      - name: Update data
        run: |
          cd python
          python3 --version
          python3 main.py

      - name: Commit to the repo
        run: |
          git config user.name "Declipsonator"
          git config user.email "null"
          git add .
          git commit -m 'Update Running Data' || echo
          git push -f origin master